load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "grpc_diagnostic_proto",
    srcs = ["grpc_diagnostic.proto"],
    strip_import_prefix = "",
)

cc_proto_library(
    name = "grpc_diagnostic_cc_proto",
    deps = [":grpc_diagnostic_proto"],
)

proto_library(
    name = "breadcrumb_proto",
    srcs = ["breadcrumb.proto"],
    strip_import_prefix = "",
)

cc_proto_library(
    name = "breadcrumb_cc_proto",
    deps = [":breadcrumb_proto"],
)
