load("@grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@grpc-java//:java_grpc_library.bzl", "java_grpc_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "modem_service_proto",
    srcs = ["modem_service.proto"],
    strip_import_prefix = "",
    deps = [
        "@protobuf//:empty_proto",
        "@protobuf//:wrappers_proto",
    ],
)

cc_proto_library(
    name = "modem_service_cc_proto",
    deps = [":modem_service_proto"],
)

cc_grpc_library(
    name = "modem_service_cc_grpc",
    srcs = [":modem_service_proto"],
    generate_mocks = True,
    grpc_only = True,
    deps = [":modem_service_cc_proto"],
)

java_proto_library(
    name = "modem_service_java_proto",
    deps = [":modem_service_proto"],
)

java_grpc_library(
    name = "modem_service_java_grpc",
    srcs = [":modem_service_proto"],
    deps = [":modem_service_java_proto"],
)
