load("@grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@grpc//bazel:python_rules.bzl", "py_proto_library")
load("@grpc-java//:java_grpc_library.bzl", "java_grpc_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "emulator_controller_proto",
    srcs = ["emulator_controller.proto"],
    strip_import_prefix = "",
    deps = ["@protobuf//:empty_proto"],
)

cc_proto_library(
    name = "emulator_controller_cc_proto",
    deps = [":emulator_controller_proto"],
)

cc_grpc_library(
    name = "emulator_controller_cc_grpc",
    srcs = [":emulator_controller_proto"],
    generate_mocks = True,
    grpc_only = True,
    deps = [":emulator_controller_cc_proto"],
)

java_proto_library(
    name = "emulator_controller_java_proto",
    deps = [":emulator_controller_proto"],
)

java_grpc_library(
    name = "emulator_controller_java_grpc",
    srcs = [":emulator_controller_proto"],
    deps = [":emulator_controller_java_proto"],
)

py_proto_library(
    name = "emulator_controller_py_proto",
    deps = [":emulator_controller_proto"],
)
