load("@grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "service_forwarder_proto",
    srcs = ["service_forwarder.proto"],
    strip_import_prefix = "",
    deps = [
        "//protos/client:grpc_endpoint_description_proto",
        "@protobuf//:empty_proto",
    ],
)

cc_proto_library(
    name = "service_forwarder_cc_proto",
    deps = [":service_forwarder_proto"],
)

cc_grpc_library(
    name = "service_forwarder_cc_grpc",
    srcs = [":service_forwarder_proto"],
    generate_mocks = True,
    grpc_only = True,
    deps = [":service_forwarder_cc_proto"],
)
