load("@grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@grpc-java//:java_grpc_library.bzl", "java_grpc_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "car_service_proto",
    srcs = ["car_service.proto"],
    strip_import_prefix = "",
    deps = ["@protobuf//:empty_proto"],
)

cc_proto_library(
    name = "car_service_cc_proto",
    deps = [":car_service_proto"],
)

cc_grpc_library(
    name = "car_service_cc_grpc",
    srcs = [":car_service_proto"],
    generate_mocks = True,
    grpc_only = True,
    deps = [":car_service_cc_proto"],
)

java_proto_library(
    name = "car_service_java_proto",
    deps = [":car_service_proto"],
)

java_grpc_library(
    name = "car_service_java_grpc",
    srcs = [":car_service_proto"],
    deps = [":car_service_java_proto"],
)

proto_library(
    name = "vehicle_service_proto",
    srcs = ["vehicle_service.proto"],
    strip_import_prefix = "",
    deps = ["@protobuf//:empty_proto"],
)

cc_proto_library(
    name = "vehicle_service_cc_proto",
    deps = [":vehicle_service_proto"],
)

cc_grpc_library(
    name = "vehicle_service_cc_grpc",
    srcs = [":vehicle_service_proto"],
    generate_mocks = True,
    grpc_only = True,
    deps = [":vehicle_service_cc_proto"],
)

java_proto_library(
    name = "vehicle_service_java_proto",
    deps = [":vehicle_service_proto"],
)

java_grpc_library(
    name = "vehicle_service_java_grpc",
    srcs = [":vehicle_service_proto"],
    deps = [":vehicle_service_java_proto"],
)
